# Generated by Django 3.1.12 on 2025-10-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=15)),
                ('budget', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=10000)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
