# Generated by Django 3.1.12 on 2025-10-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_auto_20251031_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
