# Generated by Django 3.1.12 on 2025-11-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_event',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='add_event',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
