# Generated by Django 3.1.12 on 2025-11-01 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_auto_20251101_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_event',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventapp.users'),
        ),
        migrations.AddField(
            model_name='add_event',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
